# Generated by Django 4.2.1 on 2023-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(unique=True),
        ),
    ]
