# Generated by Django 4.2.3 on 2023-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exchangerate_alter_product_image_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_to_pesos',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
